// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5fXz71TsikwuLG6kJyZhxvegXeURZTGE',
    appId: '1:937118447200:web:8b786530423857e6233505',
    messagingSenderId: '937118447200',
    projectId: 'sample-firebase-ai-app-b53ae',
    authDomain: 'sample-firebase-ai-app-b53ae.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-b53ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9DeTZWFEfIzUgM5T7RhnClaAoOW8ozEs',
    appId: '1:937118447200:android:58160a3dafd06c3e233505',
    messagingSenderId: '937118447200',
    projectId: 'sample-firebase-ai-app-b53ae',
    storageBucket: 'sample-firebase-ai-app-b53ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUksLusBgQuekc504FBFuxCOj_1pVkB5Q',
    appId: '1:937118447200:ios:74ba09394113829c233505',
    messagingSenderId: '937118447200',
    projectId: 'sample-firebase-ai-app-b53ae',
    storageBucket: 'sample-firebase-ai-app-b53ae.firebasestorage.app',
    iosBundleId: 'com.example.proyectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUksLusBgQuekc504FBFuxCOj_1pVkB5Q',
    appId: '1:937118447200:ios:74ba09394113829c233505',
    messagingSenderId: '937118447200',
    projectId: 'sample-firebase-ai-app-b53ae',
    storageBucket: 'sample-firebase-ai-app-b53ae.firebasestorage.app',
    iosBundleId: 'com.example.proyectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5fXz71TsikwuLG6kJyZhxvegXeURZTGE',
    appId: '1:937118447200:web:8e8b98f6c2d753a5233505',
    messagingSenderId: '937118447200',
    projectId: 'sample-firebase-ai-app-b53ae',
    authDomain: 'sample-firebase-ai-app-b53ae.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-b53ae.firebasestorage.app',
  );
}
